### ISSUE TITLE
Having trouble with vercel

### ISSUE THREAD

**Issue by Idfkd** [PunGrumpy/image-logger#3]
Once i get to vercel to deploy the project i don't know what to do at all
I have completed all steps for this image logger but i am not sure on how to actually use it now that i have completed everything.
Is it possible u can make a short video or even explain it?

**Comment by PunGrumpy** [comment]
## 1️⃣ Discord Webhooks

[Tutorial How to create discord webhook](https://www.youtube.com/watch?v=fKksxz2Gdnc)

## 2️⃣ Image

1. Download the image that you wanna use
2. Move the image to `src/assets` folder (If u don't have an assets folder create that)

## 3️⃣ Configuration in `config.json`

1. Copy name and webhook URL
2. Add image path 

An example: 
```json
{
  "webhooks": [
    {
      "name": "example_discord_webhook",
      "url": "https://discord.com/api/webhooks/"
    }
  ],
  "image": [
    {
      "name": "cat",
      "path": "src/assets/cat.png"
    }
  ]
}
```

## 4️⃣ Deploy to Vercel

1. Commit config to your repository (Don't forget to fork this repository) 

> [!WARNING]
> Be careful with your secretary (config.json) 

2. Deploy project to Vercel [How to deploy](https://vercel.com/docs/deployments/git/vercel-for-github)

---

> [!NOTE]
> I'm not sure if it still works on Vercel.
